package com.example.model;

import java.io.Serializable;

public class Admin implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.aid
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.aname
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private String aname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.apasswd
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private String apasswd;

    private String oldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.aid
     *
     * @return the value of admin.aid
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Admin withAid(Integer aid) {
        this.setAid(aid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.aid
     *
     * @param aid the value for admin.aid
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.aname
     *
     * @return the value of admin.aname
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Admin withAname(String aname) {
        this.setAname(aname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.aname
     *
     * @param aname the value for admin.aname
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public void setAname(String aname) {
        this.aname = aname == null ? null : aname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.apasswd
     *
     * @return the value of admin.apasswd
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public String getApasswd() {
        return apasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Admin withApasswd(String apasswd) {
        this.setApasswd(apasswd);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.apasswd
     *
     * @param apasswd the value for admin.apasswd
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public void setApasswd(String apasswd) {
        this.apasswd = apasswd == null ? null : apasswd.trim();
    }

    public String getOldName() {
        return oldName;
    }

    public void setOldName(String oldName) {
        this.oldName = oldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */

    @Override
    public String toString() {
        return "Admin{" +
                "aid=" + aid +
                ", aname='" + aname + '\'' +
                ", apasswd='" + apasswd + '\'' +
                ", oldName='" + oldName + '\'' +
                '}';
    }
}