package com.example.model;

import java.io.Serializable;

public class Area implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.saddressid
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private Integer saddressid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.saddress
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private String saddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.time
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table area
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.saddressid
     *
     * @return the value of area.saddressid
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Integer getSaddressid() {
        return saddressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Area withSaddressid(Integer saddressid) {
        this.setSaddressid(saddressid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.saddressid
     *
     * @param saddressid the value for area.saddressid
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public void setSaddressid(Integer saddressid) {
        this.saddressid = saddressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.saddress
     *
     * @return the value of area.saddress
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public String getSaddress() {
        return saddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Area withSaddress(String saddress) {
        this.setSaddress(saddress);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.saddress
     *
     * @param saddress the value for area.saddress
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public void setSaddress(String saddress) {
        this.saddress = saddress == null ? null : saddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.time
     *
     * @return the value of area.time
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Area withTime(String time) {
        this.setTime(time);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.time
     *
     * @param time the value for area.time
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", saddressid=").append(saddressid);
        sb.append(", saddress=").append(saddress);
        sb.append(", time=").append(time);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}