package com.example.model;

import java.io.Serializable;

public class Consumer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.uid
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.uname
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.upasswd
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private String upasswd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.uphone
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private String uphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.uaddress
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private String uaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.role
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private Integer role;

    private String oldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table consumer
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.uid
     *
     * @return the value of consumer.uid
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Consumer withUid(Integer uid) {
        this.setUid(uid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.uid
     *
     * @param uid the value for consumer.uid
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.uname
     *
     * @return the value of consumer.uname
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Consumer withUname(String uname) {
        this.setUname(uname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.uname
     *
     * @param uname the value for consumer.uname
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.upasswd
     *
     * @return the value of consumer.upasswd
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public String getUpasswd() {
        return upasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Consumer withUpasswd(String upasswd) {
        this.setUpasswd(upasswd);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.upasswd
     *
     * @param upasswd the value for consumer.upasswd
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public void setUpasswd(String upasswd) {
        this.upasswd = upasswd == null ? null : upasswd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.uphone
     *
     * @return the value of consumer.uphone
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public String getUphone() {
        return uphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Consumer withUphone(String uphone) {
        this.setUphone(uphone);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.uphone
     *
     * @param uphone the value for consumer.uphone
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public void setUphone(String uphone) {
        this.uphone = uphone == null ? null : uphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.uaddress
     *
     * @return the value of consumer.uaddress
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public String getUaddress() {
        return uaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Consumer withUaddress(String uaddress) {
        this.setUaddress(uaddress);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.uaddress
     *
     * @param uaddress the value for consumer.uaddress
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public void setUaddress(String uaddress) {
        this.uaddress = uaddress == null ? null : uaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.role
     *
     * @return the value of consumer.role
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Consumer withRole(Integer role) {
        this.setRole(role);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.role
     *
     * @param role the value for consumer.role
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    public String getOldName() {
        return oldName;
    }

    public void setOldName(String oldName) {
        this.oldName = oldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */

    @Override
    public String toString() {
        return "Consumer{" +
                "uid=" + uid +
                ", uname='" + uname + '\'' +
                ", upasswd='" + upasswd + '\'' +
                ", uphone='" + uphone + '\'' +
                ", uaddress='" + uaddress + '\'' +
                ", role=" + role +
                ", oldName='" + oldName + '\'' +
                '}';
    }
}