package com.example.model;

import java.io.Serializable;

public class Image implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.id
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.image
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.cid
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table image
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.id
     *
     * @return the value of image.id
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Image withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.id
     *
     * @param id the value for image.id
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.image
     *
     * @return the value of image.image
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Image withImage(String image) {
        this.setImage(image);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.image
     *
     * @param image the value for image.image
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.cid
     *
     * @return the value of image.cid
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Image withCid(Integer cid) {
        this.setCid(cid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.cid
     *
     * @param cid the value for image.cid
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", image=").append(image);
        sb.append(", cid=").append(cid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}