package com.example.model;

import java.io.Serializable;
import java.util.Date;

public class Income implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.id
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.incomesum
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private String incomesum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.amout
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private String amout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.finaltime
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private Date finaltime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.sid
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.did
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private Integer did;

    private Orders orders;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table income
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.id
     *
     * @return the value of income.id
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Income withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.id
     *
     * @param id the value for income.id
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.incomesum
     *
     * @return the value of income.incomesum
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public String getIncomesum() {
        return incomesum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Income withIncomesum(String incomesum) {
        this.setIncomesum(incomesum);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.incomesum
     *
     * @param incomesum the value for income.incomesum
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public void setIncomesum(String incomesum) {
        this.incomesum = incomesum == null ? null : incomesum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.amout
     *
     * @return the value of income.amout
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public String getAmout() {
        return amout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Income withAmout(String amout) {
        this.setAmout(amout);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.amout
     *
     * @param amout the value for income.amout
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public void setAmout(String amout) {
        this.amout = amout == null ? null : amout.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.finaltime
     *
     * @return the value of income.finaltime
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Date getFinaltime() {
        return finaltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Income withFinaltime(Date finaltime) {
        this.setFinaltime(finaltime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.finaltime
     *
     * @param finaltime the value for income.finaltime
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public void setFinaltime(Date finaltime) {
        this.finaltime = finaltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.sid
     *
     * @return the value of income.sid
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Income withSid(Integer sid) {
        this.setSid(sid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.sid
     *
     * @param sid the value for income.sid
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.did
     *
     * @return the value of income.did
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Income withDid(Integer did) {
        this.setDid(did);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.did
     *
     * @param did the value for income.did
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    public Orders getOrders() {
        return orders;
    }

    public void setOrders(Orders orders) {
        this.orders = orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */


    @Override
    public String toString() {
        return "Income{" +
                "id=" + id +
                ", incomesum='" + incomesum + '\'' +
                ", amout='" + amout + '\'' +
                ", finaltime=" + finaltime +
                ", sid=" + sid +
                ", did=" + did +
                ", orders=" + orders +
                '}';
    }
}