package com.example.model;

import java.io.Serializable;

public class Type implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.lid
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private Integer lid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.category
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table type
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.lid
     *
     * @return the value of type.lid
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Integer getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Type withLid(Integer lid) {
        this.setLid(lid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.lid
     *
     * @param lid the value for type.lid
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public void setLid(Integer lid) {
        this.lid = lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.category
     *
     * @return the value of type.category
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public Type withCategory(String category) {
        this.setCategory(category);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.category
     *
     * @param category the value for type.category
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbg.generated Fri Jan 06 22:29:42 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lid=").append(lid);
        sb.append(", category=").append(category);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}